import type * as React from 'react';

export type IconName =
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'bell'
  | 'calendar'
  | 'check'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'clock'
  | 'close'
  | 'code'
  | 'copy'
  | 'database'
  | 'download'
  | 'edit'
  | 'external-link'
  | 'eye'
  | 'file'
  | 'filter'
  | 'folder'
  | 'github'
  | 'globe'
  | 'heart'
  | 'home'
  | 'image'
  | 'info'
  | 'layers'
  | 'link'
  | 'lock'
  | 'log-out'
  | 'mail'
  | 'menu'
  | 'minus'
  | 'moon'
  | 'more'
  | 'package'
  | 'plus'
  | 'refresh'
  | 'save'
  | 'search'
  | 'send'
  | 'settings'
  | 'share'
  | 'shield'
  | 'sliders'
  | 'star'
  | 'sun'
  | 'terminal'
  | 'thumbs-up'
  | 'trash'
  | 'upload'
  | 'user'
  | 'warning'
  | 'x-circle'
  | 'zap';

export interface IconProps extends React.SVGAttributes<SVGSVGElement> {
  name: IconName;
  /** 像素尺寸，默认 16 */
  size?: number;
  /** 默认 true；仅装饰性图标应保持 true */
  decorative?: boolean;
}
